_base_: 'deeplabv2_resnet50_os8_cityscapes_1024x512_80k.yml'
batch_size: 6
model:
  backbone:
    type: ResNet101_vd
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
